; generated by Snapmaker Orca 2.1.0
; filament_type = PLA;PLA;PETG;TPU;PLA;PETG;TPU;PETG
; filament_colour = #FF0000;#FFFFFF;#0080FF;#FFFF00;#000000;#00FFFF;#FF00FF;#80FF00
; filament_settings_id = Generic PLA;Generic PLA;Generic PETG;Generic TPU;Generic PLA;Generic PETG;Generic TPU;Generic PETG
; nozzle_temperature = 220;220;235;210;220;235;210;235
; filament_diameter = 1.75;1.75;1.75;1.75;1.75;1.75;1.75;1.75
; layer_count = 80
; total_toolchanges = 7
G28 ; home all axes
G1 Z5 F5000
T0
G1 X10 Y10 Z0.2 F3000
; --- layer 1 ---
G1 X50 Y10 E1.0
G1 X50 Y50 E2.0
T1
G1 X60 Y60 E3.0
T2
G1 X70 Y70 E4.0
T4
G1 X80 Y80 E5.0
T5
G1 X90 Y90 E6.0
T6
G1 X100 Y100 E7.0
T7
G1 X110 Y110 E8.0
T0
G1 X120 Y120 E9.0
; --- layer 40 ---
T3
G1 X130 Y130 E10.0
T4
G1 X140 Y140 E11.0
M104 S0
M140 S0
M84
